name: Broadcaster
main: com.github.xrevolut1onzx.broadcaster.Broadcaster
version: 2.1
commands:
    broadcaster:
        description: Broadcaster commands
        usage: /broadcaster [broadcast/preview/reload]