name: BroadcastDonator
main: xrevolut1onzx.broadcastdonator.BroadcastDonator
version: 1.1.0
commands:
    bd:
        description: Used to display the set donator message
        usage: /<command> [reload/broadcast/preview]