name: BroadcastDonator
main: xrevolut1onzx.broadcastdonator.BroadcastDonator
version: 1.2.2
commands:
    reload:
        description: Reloads the plugin
        usage: /bd reload
    preview:
        description: Previews the message being broadcasted
        usage: /bd preview
    broadcast:
        description: Broadcasts the loaded message to applicable people
        usage: /bd broadcast